apiVersion: v1
kind: Secret
metadata:
  name: ai-tutor-grafana-cloud-secret
type: Opaque
stringData:
  GRAFANA_CLOUD_PROMETHEUS_URL: "https://prometheus-prod-56-prod-us-east-2.grafana.net/api/prom/push"
  GRAFANA_CLOUD_PROMETHEUS_USER: "<grafana-cloud-prometheus-user>"
  GRAFANA_CLOUD_PROMETHEUS_PASSWORD: "<grafana-cloud-prometheus-token>"
